language: c
os:
  - linux
sudo: false
script:
  - "clang -coverage -c -Wall *.c"
  - "gcov calc.gcno"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
      - curl
      - wget
      - gcc
      - curl
