language: c
os:
  - linux
sudo: false
script:
  - "gcc -coverage -fprofile-arcs -c -Wall calc.c -o calc"
  - "./calc.o"
  - "gcov calc.c"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
      - curl
      - wget
      - gcc
      - curl
