language: c
os:
  - linux
sudo: false
script:
  - "cd ./src"
  - "gcc ./calc/calc.c -o ./calc/calc"
  - "gcc ./auswahl/auswahl.c -o ./auswahl/auswahl"
  - "gcc ./figure/figure.c -o ./figure/figure"
  - "gcc ./lotto/lotto.c -o ./lotto/lotto"
  - "gcc ./readfile/readfile.c -o ./readfile/readfile"
  - "cd ./tictactoe"
  - "make"
  - "make test"
